---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/60519ac201783300163ba465/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Site configuration
  templates:
  - config
- type: directory
  path: data/team
  label: Person
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - person
- type: directory
  path: data/categories
  label: Category
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - category
- type: directory
  path: data/tags
  label: Tag
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - tag
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - page
  - post
  - advanced
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
